### ISSUE TITLE
D5.1 Table Of Contents

### ISSUE THREAD

**Issue by fyedro** [TBFY/knowledge-graph#15]
**Table Of Contents**
1. Introduction
2. Publication and accessibility of procurement data and knowledge graphs
  2.1 Identifying best practices
  2.2 Standards procurement data currently being published
  2.3 Practical approaches for the publication of procurement knowledge graphs
  2.4 Defining holistic standards
    2.4.1 How to publish enriched data produced over the course of the project
    2.4.2 Guidelines for the publication of open procurement data
    2.4.3 Guidelines for procurement data sharing for those sources of data which will remain private
3. Publication and governance of open procurement data
  3.1 Technical standards for the publication of open procurement data
  3.2	Licensing standards for the publication of enriched open procurement data
  3.3	Data governance standards for the management, maintenance and updating of open procurement data
4. Legal aspects of sharing and reusing closed data relevant to procurement scenarios
5. Complexities of using specific datasets in national and cross-border scenarios
6. References

This is an initial draft of the D5.1 Table of Contents, its content may be modified throughout the development of the document.

**Comment by ocorcho** [comment]
Updated ToC done in commit ecc9b3d

New ToC available at https://github.com/TBFY/knowledge-graph/blob/master/docs/D5_1%20ToC.md
