### ISSUE TITLE
Automatic CPV categorisation for Spanish

### ISSUE THREAD

**Issue by ocorcho** [TBFY/knowledge-graph#20]
UPM to check whether CPV categorisation tools from OpenOpps (based on a Bayesian classifier) can be used in Spanish

**Comment by ocorcho** [comment]
Request @woodbine for the current code, so as to see whether it can be applied with Spanish tenders.
Observers: @laurafl @ocorcho @runobe

**Comment by woodbine** [comment]
@ocorcho We'll need to set up time with our dev to explain the way the code works (I only know roughly how it works), can we do this after the API demo?
