### ISSUE TITLE
Collect business case queries for requirements analysis

### ISSUE THREAD

**Issue by ocorcho** [TBFY/knowledge-graph#22]
Business case owners should provide typical queries (data access needs) that they need to solve in their business cases, so as to determine requirements for the knowledge graph model

- [ ] ZGZ/OESIA Networks/UPM
- [ ] CERVED
- [ ] OpenCorporates
- [ ] MJU/JSI

**Comment by ocorcho** [comment]
@laurafl @runobe to provide links to @elvesater about the current SPARQL queries (e.g., to derive indicators) that are being used in Zaragoza's public procurement set. Link to the corresponding PPROC GitHub repository may be enough.

**Comment by ocorcho** [comment]
Other partners should also provide these data access needs, when they are clearer

**Comment by runobe** [comment]
@elvesater  The link commented by @ocorcho with examples of SPARQL queries that are being used in Zaragoza's public procurement set is : [http://zaragoza-sedeelectronica.github.io/sparql/queries/perfil-contratante/](http://zaragoza-sedeelectronica.github.io/sparql/queries/perfil-contratante/)

**Comment by elvesater** [comment]
Requirements collected at https://docs.google.com/spreadsheets/d/1lflsBkTQ8WguJxol-6uDmf0TZFcwGUoMPSAOeoyceUs/edit?usp=sharing
