### ISSUE TITLE
Organisation URIs

### ISSUE THREAD

**Issue by fyedro** [TBFY/knowledge-graph#37]
In order to maintain homogeneity when naming the URIs resource, we would need the structure to be of type: “namespace/resource/identifier” as it is currently in the case of "Tender", "Award", "Contract" or "ContractingProcess". Examples:
http://data.tbfy.eu/tender/ocds-0c46vo-0012-329224_329224
http://data.tbfy.eu/award/ocds-0c46vo-0001-02f25542-7be1-42f8-a670-873fe39f2cd7_1bef4ef5-d95d-47b0-9baf-9db8564688e3
http://data.tbfy.eu/contract/ocds-0c46vo-0009-DN385028-1_1
http://data.tbfy.eu/contractingProcess/ocds-0c46vo-0009-DN379620-1
but not in the case of organisations:
http://data.tbfy.eu/company/gb/05943167
1) Could the jurisdiction of the URI be removed or the "/" replaced by "-"? (i.e: http://data.tbfy.eu/company/05943167 or http://data.tbfy.eu/company/gb-05943167). 
2) (not critical) Just for not changing the name of the resource in the core API, is it possible to rename company for organisation?

**Comment by fyedro** [comment]
Regarding point 2, likely not all results are companies so, despite having indicated that it is not critical, we think that /company/ should be renamed to /organisation/, if possible

**Comment by elvesater** [comment]
Updated mapping rules for company. Replaced "company" with "organisation" in the URI. Replaced "{jurisdiction_code}/{company_number}" with "{jurisdiction_code}-{company_number}" in the URI. Changes committed to the develop branch. Will merge with master branch after other change requests have been implemented.
