### ISSUE TITLE
Milestone class identifier

### ISSUE THREAD

**Issue by fyedro** [TBFY/knowledge-graph#38]
observing the predicates of the Milestone class in the KG, you get:

1 | rdf:type
2 | dct:description
3 | dct:title
4 | http://data.tbfy.eu/ontology/ocds#documentId
5 | http://data.tbfy.eu/ontology/ocds#milestoneDueDate

number 4 should not be http://data.tbfy.eu/ontology/ocds#milestonetId?
documentId does not belong to the Milestone class according to the ontology.

**Comment by ahmet-soylu** [comment]
@elvesater, it is correct that it should be milestoneId for Milestone class. The mapping needs to be fixed.

**Comment by elvesater** [comment]
Fixed mapping rules for milestones. Committed to the develop branch. Will merge with master branch and create new release after other issues have been closed.
