### ISSUE TITLE
Provide a list of public entities in each country

### ISSUE THREAD

**Issue by fyedro** [TBFY/knowledge-graph#7]
All to let OO know if their country has a list of public entities and how to access it. If there is none, but the participant is able to create one, let OO know the method and sources used to create the list

**Comment by ocorcho** [comment]
If there is none, but we are able to create one, let OO know the method and sources used to create the list

**Comment by ocorcho** [comment]
Spain: http://www.minhafp.gob.es/es-ES/GobiernoAbierto/Datos%20Abiertos/Paginas/CatalogoRISPSecretariadeEstadodeAdministracionesPublicas.aspx (look for DIR3 and there are several files there)

**Comment by laurafl** [comment]
Another page where you can consult the public entities of Spain. To access the listings, go to the section "Consulta de unidades y oficinas en DIR3": https://administracionelectronica.gob.es/ctt/dir3/descargas#.WqZ9MCVxxRQ

**Comment by fyedro** [comment]
The following links couldn't be scraped:
- http://www.provincia.vicenza.it/vi-abilita-amministrazione-trasparente-struttura/bandi-di-concorso/bandi-di-concorso_1
- www.vitoria-gasteiz.org
- www.sevilla.org
- www.contratacion.euskadi.eus
