### ISSUE TITLE
Send OO details of work already done on tagging

### ISSUE THREAD

**Issue by fyedro** [TBFY/knowledge-graph#9]
UPM to send OO details of work already done on tagging

**Comment by fyedro** [comment]
[HNER.docx](https://github.com/TBFY/knowledge-graph/files/1789051/HNER.docx)

**Comment by fyedro** [comment]
[HNER.docx](https://github.com/TBFY/knowledge-graph/files/1789068/HNER.docx)

HNER Information pack

**Comment by ocorcho** [comment]
Initial description available at https://github.com/TBFY/knowledge-graph/blob/master/docs/EntityExtractor-UPM.md
